### ISSUE TITLE
Köszönöm :)

### ISSUE THREAD

**Issue by nemesszili** [dlt-rilmta/hadifogoly-adatbazis#1]
Nem hittem volna, hogy a nagyszüleim ennyire fognak örülni egy github repónak, de ezt is megértük. Köszönöm, hogy ezt megcsináltátok!

Pár kérdés:
1. Bár az adatlapokon is megtaláltam távozás dátumát (mondjuk az évszámot nem tudom tisztán kivenni), ez metaadatként is érkezett az oroszoktól vagy csak a felvételekből nyeritek ki?
2. Találtam egy jó forrást hadifogolytáborokról: https://hadisir.hu/szovjet-hadifogolytaborok - vajon megoldható lenne, hogy ha az illető tábor jelen van ebben az adatbázisban, akkor az oldalon is legyen egy átirányítás ehhez vagy feltüntetni, hogy milyen település mellett volt a Szovjetunióban? Esetleg tudjátok, hogy ez az adathalmaz elérhető-e publikusan?
3. Érthető, hogy nem tehetitek publikussá a kinyert adatokat, de anonimizálva megoldható lenne? Szerintem hatalmas vizualizációs potenciálja lenne, már lenne is pár ötletem. :-)
4. Ha megtaláltam egy felmenőmet és többet szeretnék megtudni arról, hogy hol harcolhatott, milyen alakulatban, hol lenne érdemes tovább érdeklődni? Honvédelmi minisztérium?

**Comment by sassbalint** [comment]
Nagyon köszönöm a reakciót. Nem sokban tudok segíteni, mi (Nyelvtud Kutközpont) "csak" a magyar nyelvű adatok helyreállítását csináltuk a cirill betűkkel leírt formából kiindulva. A projekt gazdája a Magyar Nemzeti Levéltár, ők tudhatnak többet, de azért ld. alább.

> Nem hittem volna, hogy a nagyszüleim ennyire fognak örülni egy github repónak, de ezt is megértük.

:smiley: :smiley:

> Köszönöm, hogy ezt megcsináltátok!

:heart:

> Pár kérdés:
> 
> 1. Bár az adatlapokon is megtaláltam távozás dátumát (mondjuk az évszámot nem tudom tisztán kivenni), ez metaadatként is érkezett az oroszoktól vagy csak a felvételekből nyeritek ki?

A [keresőben lévő adatlapokra](https://adatbazisokonline.hu/adatbazis/szovjet-taborok-magyar-foglyai) gondolsz? Minden "metaadatként" érkezett, mi semmit nem nyertünk ki a felvételekből (= digitalizált szkennelt kartonokból), hanem csakis az oroszok által készített szöveges adatbázisból dolgoztunk. Ennek szerkezete [tanulmányozható a mellékelt pszeudoadaton.](https://github.com/dlt-rilmta/hadifogoly-adatbazis/blob/main/data/pseudo_1000_42.csv)
 
> 2. Találtam egy jó forrást hadifogolytáborokról: [hadisir.hu/szovjet-hadifogolytaborok](https://hadisir.hu/szovjet-hadifogolytaborok) - vajon megoldható lenne, hogy ha az illető tábor jelen van ebben az adatbázisban, akkor az oldalon is legyen egy átirányítás ehhez vagy feltüntetni, hogy milyen település mellett volt a Szovjetunióban? Esetleg tudjátok, hogy ez az adathalmaz elérhető-e publikusan?

Igen, van a `hadisir.hu`, annyit mondhatok, hogy a https://adatbazisokonline.hu/adatbazis/szovjet-taborok-magyar-foglyai oldal "1.0-s verzió", jópár további terve van a Levéltárnak az adatbázissal/felülettel. :) Nem tudok róla, hogy a `hadisir.hu` adatbázisa elérhető lenne publikusan.

> 3. Érthető, hogy nem tehetitek publikussá a kinyert adatokat, de anonimizálva megoldható lenne? Szerintem hatalmas vizualizációs potenciálja lenne, már lenne is pár ötletem. :-)

Az adat birtokosa a Levéltár, mi (Nyelvtud Kutközpont) biztos, hogy nem tehetjük közzé anonimizálva se. Ezzel és az ötletekkel esetleg keresd meg a Levéltárat. Pontosabban: az ötletek érdekelnek engem is. :)

> 4. Ha megtaláltam egy felmenőmet és többet szeretnék megtudni arról, hogy hol harcolhatott, milyen alakulatban, hol lenne érdemes tovább érdeklődni? Honvédelmi minisztérium?

Ezt nem tudom sajnos. Én azt hiszem, a Levéltárhoz fordulnék.

Kösz szépen a visszajelzést! :)

**Comment by nemesszili** [comment]
> A [keresőben lévő adatlapokra](https://adatbazisokonline.hu/adatbazis/szovjet-taborok-magyar-foglyai) gondolsz? 

Igen, ezek az adatlapok.

> > Minden "metaadatként" érkezett, mi semmit nem nyertünk ki a felvételekből (= digitalizált szkennelt kartonokból), hanem csakis az oroszok által készített szöveges adatbázisból dolgoztunk. Ennek szerkezete [tanulmányozható a mellékelt pszeudoadaton.](https://github.com/dlt-rilmta/hadifogoly-adatbazis/blob/main/data/pseudo_1000_42.csv)

Tiszta!

> Igen, van a hadisir.hu, annyit mondhatok, hogy a https://adatbazisokonline.hu/adatbazis/szovjet-taborok-magyar-foglyai oldal "1.0-s verzió", jópár további terve van a Levéltárnak az adatbázissal/felülettel. :)

Jó hallani. :) Fél szemmel majd követem.

> Nem tudok róla, hogy a hadisir.hu adatbázisa elérhető lenne publikusan.

Kár, pedig ezesetben nem hinném, hogy ez személyi jogokat sértene, ha publikus lenne.

> Ezzel és az ötletekkel esetleg keresd meg a Levéltárat. Pontosabban: az ötletek érdekelnek engem is. :)

Oké, még jelentkezem! :)

> Ezt nem tudom sajnos. Én azt hiszem, a Levéltárhoz fordulnék.

Köszi az eligazítást.
